export const CREATE_TOKEN_FAILED = 'CREATE_TOKEN_FAILED';
export const UPDATE_TOKEN_FAILED = 'UPDATE_TOKEN_FAILED';
export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const INVALID_TOKEN = 'INVALID_TOKEN';
export const UNAUTHORIZE = 'UNAUTHORIZE';




