export const ERR_CREATE_PRODUCT = "ERR_CREATE_PRODUCT";
export const ERR_GET_PRODUCT_LIST = "ERR_GET_PRODUCT_LIST";
export const ERR_UPDATE_PRODUCT = "ERR_UPDATE_PRODUCT";
export const ERR_DELETE_PRODUCT = "ERR_DELETE_PRODUCT";
export const ERR_MISSING_INPUT = "ERR_MISSING_INPUT";