export const ERR_CREATE_CATEGORY = "ERR_CREATE_PRODUCT";
export const ERR_GET_CATEGORY_LIST = "ERR_GET_PRODUCT_LIST";
export const ERR_UPDATE_CATEGORY = "ERR_UPDATE_PRODUCT";
export const ERR_DELETE_CATEGORY = "ERR_DELETE_PRODUCT";